version: '2.4'

services:
  mlat-client:
    image: docker.io/blackoutsecure/mlat-client:latest
    container_name: mlat-adsbx
    environment:
      TZ: Etc/UTC
      MLAT_CLIENT_INPUT_CONNECT: 'readsb:30005'
      MLAT_CLIENT_SERVER: 'feed.adsbexchange.com:31090'
      MLAT_CLIENT_AUTO_LOCATION: 'true'
      MLAT_CLIENT_USER_ID: 'changeme'
      MLAT_CLIENT_RESULTS: 'beast,connect,readsb:30104'
      LOG_LEVEL: 'info'              # debug | info | warn | error | fatal
    volumes:
      - mlat-config:/config
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    tmpfs:
      - /tmp
      - /run:exec
    restart: unless-stopped

volumes:
  mlat-config:
