version: '2.4'

services:
  mlat-client:
    image: docker.io/blackoutsecure/mlat-client:latest
    container_name: mlat-client
    environment:
      TZ: Etc/UTC
      MLAT_CLIENT_INPUT_CONNECT: 'readsb:30005'
      MLAT_CLIENT_SERVER: 'feed.adsbexchange.com:31090'
      MLAT_CLIENT_AUTO_LOCATION: 'true'
      MLAT_CLIENT_LAT: ''
      MLAT_CLIENT_LON: ''
      MLAT_CLIENT_ALT: ''
      MLAT_CLIENT_USER_ID: 'changeme'
      MLAT_CLIENT_RESULTS: 'beast,connect,readsb:30104'
    volumes:
      - config:/config
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /run:exec
    read_only: false
    restart: unless-stopped

volumes:
  config:
